/**
 * Restore the DB function/trigger layer that drizzle-kit push does not create.
 *
 * Extracts every CREATE [OR REPLACE] FUNCTION / CREATE [OR REPLACE] TRIGGER /
 * DROP FUNCTION|TRIGGER / ALTER FUNCTION / COMMENT ON FUNCTION / GRANT|REVOKE ON
 * FUNCTION statement from supabase/migrations/*.sql (in filename order, so the
 * latest definition of each object wins), writes a consolidated migration file,
 * then applies each statement to the DB in order — continuing on error and
 * reporting every failure (no silent skips).
 *
 * Usage: DATABASE_URL=... NODE_EXTRA_CA_CERTS=./cert.pem.crt npx tsx scripts/restoreDbObjects.ts
 */
import pg from "pg";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL) {
  console.error("ERROR: DATABASE_URL not set.");
  process.exit(1);
}

const MIG_DIR = "supabase/migrations";
const OUT_FILE = join(MIG_DIR, "20260721210000_restore_functions_triggers.sql");
// Skip this session's non-historical migrations (no functions/triggers) + the output file itself.
const SKIP = /^20260721(195500|200000|210000)/;

function splitStatements(sql: string): string[] {
  const out: string[] = [];
  let cur = "";
  let i = 0;
  const n = sql.length;
  while (i < n) {
    const ch = sql[i];
    if (ch === "-" && sql[i + 1] === "-") {
      const nl = sql.indexOf("\n", i);
      const end = nl === -1 ? n : nl;
      cur += sql.slice(i, end);
      i = end;
      continue;
    }
    if (ch === "/" && sql[i + 1] === "*") {
      const close = sql.indexOf("*/", i + 2);
      const end = close === -1 ? n : close + 2;
      cur += sql.slice(i, end);
      i = end;
      continue;
    }
    if (ch === "'") {
      let j = i + 1;
      while (j < n) {
        if (sql[j] === "'" && sql[j + 1] === "'") { j += 2; continue; }
        if (sql[j] === "'") { j++; break; }
        j++;
      }
      cur += sql.slice(i, j);
      i = j;
      continue;
    }
    if (ch === "$") {
      const m = /^\$[A-Za-z0-9_]*\$/.exec(sql.slice(i));
      if (m) {
        const tag = m[0];
        const close = sql.indexOf(tag, i + tag.length);
        const end = close === -1 ? n : close + tag.length;
        cur += sql.slice(i, end);
        i = end;
        continue;
      }
    }
    if (ch === ";") {
      cur += ";";
      if (cur.trim()) out.push(cur.trim());
      cur = "";
      i++;
      continue;
    }
    cur += ch;
    i++;
  }
  if (cur.trim()) out.push(cur.trim());
  return out;
}

function stripLeadingComments(s: string): string {
  let t = s;
  for (;;) {
    const before = t;
    t = t.replace(/^\s+/, "").replace(/^--[^\n]*\n?/, "").replace(/^\/\*[\s\S]*?\*\//, "");
    if (t === before) return t;
  }
}

const TARGET =
  /^(create\s+(or\s+replace\s+)?function|create\s+(or\s+replace\s+)?trigger|drop\s+trigger|drop\s+function|alter\s+function|comment\s+on\s+function|grant\b[\s\S]*?\bon\s+function|revoke\b[\s\S]*?\bon\s+function)\b/i;

async function main() {
  const files = readdirSync(MIG_DIR).filter((f) => /\.sql$/.test(f) && !SKIP.test(f)).sort();
  const kept: { file: string; stmt: string }[] = [];
  for (const f of files) {
    const sql = readFileSync(join(MIG_DIR, f), "utf8");
    for (const stmt of splitStatements(sql)) {
      if (TARGET.test(stripLeadingComments(stmt))) kept.push({ file: f, stmt });
    }
  }
  console.log(`Scanned ${files.length} migration files -> ${kept.length} function/trigger DDL statements.`);

  const header =
    "-- Restore DB function/trigger layer (extracted from historical migrations, in order).\n" +
    "-- drizzle-kit push builds tables only; this reproduces the function/trigger layer.\n" +
    "-- Auto-generated by scripts/restoreDbObjects.ts.\n\n";
  writeFileSync(OUT_FILE, header + kept.map((k) => `-- from ${k.file}\n${k.stmt}\n`).join("\n"));
  console.log(`Wrote ${OUT_FILE} (${kept.length} statements).`);

  const pool = new pg.Pool({ connectionString: DATABASE_URL, max: 1 });
  const client = await pool.connect();
  let ok = 0;
  const failures: { file: string; head: string; error: string }[] = [];
  for (const { file, stmt } of kept) {
    try {
      await client.query(stmt);
      ok++;
    } catch (e) {
      failures.push({
        file,
        head: stripLeadingComments(stmt).slice(0, 100).replace(/\s+/g, " "),
        error: (e as Error).message,
      });
    }
  }

  const q = async (sql: string) => (await client.query(sql)).rows[0].n as number;
  const fnCount = await q("select count(distinct proname)::int n from pg_proc p join pg_namespace nn on nn.oid=p.pronamespace where nn.nspname='public'");
  const trgPub = await q("select count(*)::int n from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace nn on nn.oid=c.relnamespace where nn.nspname='public' and not t.tgisinternal");
  const trgAuth = await q("select count(*)::int n from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_namespace nn on nn.oid=c.relnamespace where nn.nspname='auth' and not t.tgisinternal");
  client.release();
  await pool.end();

  console.log("\n=== APPLY RESULT ===");
  console.log(`applied OK: ${ok}/${kept.length}   failed: ${failures.length}`);
  if (failures.length) {
    console.log("--- failures (no silent skips) ---");
    for (const f of failures) console.log(`FAIL [${f.file}] ${f.head}\n   -> ${f.error}`);
  }
  console.log("\n=== FINAL COUNTS ===");
  console.log(`public functions (unique): ${fnCount}`);
  console.log(`public triggers: ${trgPub}`);
  console.log(`auth triggers:   ${trgAuth}`);
  console.log(`has_capability present: ${fnCount >= 0 ? "(see verification step)" : ""}`);
}

main().catch((e) => { console.error(e); process.exit(1); });
