-- Restore DB function/trigger layer (extracted from historical migrations, in order).
-- drizzle-kit push builds tables only; this reproduces the function/trigger layer.
-- Auto-generated by scripts/restoreDbObjects.ts.

-- from 20250818093742_539006f2-a021-405e-b780-92b4b3e3dbff.sql
-- Fix function search path security issue
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER 
LANGUAGE plpgsql
SECURITY DEFINER 
SET search_path = public
AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$;

-- from 20250818093742_539006f2-a021-405e-b780-92b4b3e3dbff.sql
-- Update the handle_new_user function with proper security
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER 
SET search_path = public
AS $$
BEGIN
  -- This trigger will be used when we implement auth
  -- For now, users will be created manually
  RETURN NEW;
END;
$$;

-- from 20250818095855_bf99678d-33b3-4e57-9580-2bc7c78aca2d.sql
-- Add trigger for role_assignments updated_at
CREATE TRIGGER update_role_assignments_updated_at
BEFORE UPDATE ON role_assignments
FOR EACH ROW
EXECUTE FUNCTION update_updated_at_column();

-- from 20250818105645_dbec80ed-6fe2-44d3-87aa-f6702ef8c836.sql
-- Create security definer functions to avoid recursive policy lookups
CREATE OR REPLACE FUNCTION public.get_user_practice_id(user_id uuid)
RETURNS uuid AS $$
  SELECT practice_id FROM public.users WHERE auth_user_id = user_id;
$$ LANGUAGE SQL SECURITY DEFINER STABLE;

-- from 20250818105645_dbec80ed-6fe2-44d3-87aa-f6702ef8c836.sql
CREATE OR REPLACE FUNCTION public.is_practice_manager(user_id uuid)
RETURNS boolean AS $$
  SELECT COALESCE(is_practice_manager, false) FROM public.users WHERE auth_user_id = user_id;
$$ LANGUAGE SQL SECURITY DEFINER STABLE;

-- from 20250818105806_c5688bbe-e17a-4445-89fa-ce95e61ca1e8.sql
-- Fix security warnings by adding search_path to functions
DROP FUNCTION IF EXISTS public.get_user_practice_id(uuid);

-- from 20250818105806_c5688bbe-e17a-4445-89fa-ce95e61ca1e8.sql
DROP FUNCTION IF EXISTS public.is_practice_manager(uuid);

-- from 20250818105806_c5688bbe-e17a-4445-89fa-ce95e61ca1e8.sql
-- Recreate functions with proper search_path
CREATE OR REPLACE FUNCTION public.get_user_practice_id(user_id uuid)
RETURNS uuid AS $$
  SELECT practice_id FROM public.users WHERE auth_user_id = user_id;
$$ LANGUAGE SQL SECURITY DEFINER STABLE SET search_path = public;

-- from 20250818105806_c5688bbe-e17a-4445-89fa-ce95e61ca1e8.sql
CREATE OR REPLACE FUNCTION public.is_practice_manager(user_id uuid)
RETURNS boolean AS $$
  SELECT COALESCE(is_practice_manager, false) FROM public.users WHERE auth_user_id = user_id;
$$ LANGUAGE SQL SECURITY DEFINER STABLE SET search_path = public;

-- from 20250818105901_001be93f-e806-427f-9c34-cd3dbb473f85.sql
-- Fix search_path for functions by replacing them with CASCADE
DROP FUNCTION public.get_user_practice_id(uuid) CASCADE;

-- from 20250818105901_001be93f-e806-427f-9c34-cd3dbb473f85.sql
DROP FUNCTION public.is_practice_manager(uuid) CASCADE;

-- from 20250818105901_001be93f-e806-427f-9c34-cd3dbb473f85.sql
-- Recreate functions with proper search_path
CREATE OR REPLACE FUNCTION public.get_user_practice_id(user_id uuid)
RETURNS uuid AS $$
  SELECT practice_id FROM public.users WHERE auth_user_id = user_id;
$$ LANGUAGE SQL SECURITY DEFINER STABLE SET search_path = public;

-- from 20250818105901_001be93f-e806-427f-9c34-cd3dbb473f85.sql
CREATE OR REPLACE FUNCTION public.is_practice_manager(user_id uuid)
RETURNS boolean AS $$
  SELECT COALESCE(is_practice_manager, false) FROM public.users WHERE auth_user_id = user_id;
$$ LANGUAGE SQL SECURITY DEFINER STABLE SET search_path = public;

-- from 20250822145649_7277eb92-ffdc-42b3-8192-fc7bdef4222b.sql
-- Create function to check if user is master user
CREATE OR REPLACE FUNCTION public.is_master_user(user_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path TO 'public'
AS $function$
  SELECT COALESCE(is_master_user, false) FROM public.users WHERE auth_user_id = user_id;
$function$;

-- from 20250822154328_551b0c71-912a-472e-851f-5a8b80306c1d.sql
-- Create security definer functions to get user properties without recursion
CREATE OR REPLACE FUNCTION public.get_current_user_practice_id()
RETURNS uuid
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
  SELECT practice_id FROM public.users WHERE auth_user_id = auth.uid();
$$;

-- from 20250822154328_551b0c71-912a-472e-851f-5a8b80306c1d.sql
CREATE OR REPLACE FUNCTION public.is_current_user_practice_manager()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
  SELECT COALESCE(is_practice_manager, false) FROM public.users WHERE auth_user_id = auth.uid();
$$;

-- from 20250822154328_551b0c71-912a-472e-851f-5a8b80306c1d.sql
CREATE OR REPLACE FUNCTION public.is_current_user_master()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
  SELECT COALESCE(is_master_user, false) FROM public.users WHERE auth_user_id = auth.uid();
$$;

-- from 20250822154359_ee5ed570-4e26-4d17-8dbe-e2c9282897bc.sql
-- Fix security definer functions with proper search path
CREATE OR REPLACE FUNCTION public.get_current_user_practice_id()
RETURNS uuid
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT practice_id FROM public.users WHERE auth_user_id = auth.uid();
$$;

-- from 20250822154359_ee5ed570-4e26-4d17-8dbe-e2c9282897bc.sql
CREATE OR REPLACE FUNCTION public.is_current_user_practice_manager()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT COALESCE(is_practice_manager, false) FROM public.users WHERE auth_user_id = auth.uid();
$$;

-- from 20250822154359_ee5ed570-4e26-4d17-8dbe-e2c9282897bc.sql
CREATE OR REPLACE FUNCTION public.is_current_user_master()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT COALESCE(is_master_user, false) FROM public.users WHERE auth_user_id = auth.uid();
$$;

-- from 20251006134548_aedd5378-fa7c-4657-8694-61d0a7c7ac96.sql
-- Add updated_at triggers
CREATE TRIGGER update_groups_updated_at BEFORE UPDATE ON public.groups
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- from 20251006134548_aedd5378-fa7c-4657-8694-61d0a7c7ac96.sql
CREATE TRIGGER update_task_templates_updated_at BEFORE UPDATE ON public.task_templates
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- from 20251006134548_aedd5378-fa7c-4657-8694-61d0a7c7ac96.sql
CREATE TRIGGER update_tasks_updated_at BEFORE UPDATE ON public.tasks
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- from 20251006134548_aedd5378-fa7c-4657-8694-61d0a7c7ac96.sql
CREATE TRIGGER update_form_templates_updated_at BEFORE UPDATE ON public.form_templates
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- from 20251006134548_aedd5378-fa7c-4657-8694-61d0a7c7ac96.sql
CREATE TRIGGER update_form_submissions_updated_at BEFORE UPDATE ON public.form_submissions
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- from 20251006135054_3ab65600-d22a-4a7f-a76f-1630fe92c7c7.sql
-- Triggers
DROP TRIGGER IF EXISTS update_groups_updated_at ON public.groups;

-- from 20251006135054_3ab65600-d22a-4a7f-a76f-1630fe92c7c7.sql
DROP TRIGGER IF EXISTS update_task_templates_updated_at ON public.task_templates;

-- from 20251006135054_3ab65600-d22a-4a7f-a76f-1630fe92c7c7.sql
DROP TRIGGER IF EXISTS update_tasks_updated_at ON public.tasks;

-- from 20251006135054_3ab65600-d22a-4a7f-a76f-1630fe92c7c7.sql
DROP TRIGGER IF EXISTS update_form_templates_updated_at ON public.form_templates;

-- from 20251006135054_3ab65600-d22a-4a7f-a76f-1630fe92c7c7.sql
DROP TRIGGER IF EXISTS update_form_submissions_updated_at ON public.form_submissions;

-- from 20251006135054_3ab65600-d22a-4a7f-a76f-1630fe92c7c7.sql
CREATE TRIGGER update_groups_updated_at BEFORE UPDATE ON public.groups
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- from 20251006135054_3ab65600-d22a-4a7f-a76f-1630fe92c7c7.sql
CREATE TRIGGER update_task_templates_updated_at BEFORE UPDATE ON public.task_templates
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- from 20251006135054_3ab65600-d22a-4a7f-a76f-1630fe92c7c7.sql
CREATE TRIGGER update_tasks_updated_at BEFORE UPDATE ON public.tasks
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- from 20251006135054_3ab65600-d22a-4a7f-a76f-1630fe92c7c7.sql
CREATE TRIGGER update_form_templates_updated_at BEFORE UPDATE ON public.form_templates
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- from 20251006135054_3ab65600-d22a-4a7f-a76f-1630fe92c7c7.sql
CREATE TRIGGER update_form_submissions_updated_at BEFORE UPDATE ON public.form_submissions
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- from 20251006135200_d13583c1-7d2c-45f7-a42c-a27f0c8e1846.sql
-- Phase 1b: RLS Policies for all new tables

-- Helper functions for role checks (using existing patterns)
CREATE OR REPLACE FUNCTION public.is_group_manager(user_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE SECURITY DEFINER
SET search_path = 'public'
AS $$
  SELECT COALESCE(
    EXISTS(
      SELECT 1 FROM public.users 
      WHERE auth_user_id = user_id 
      AND role = 'group_manager'
    ), 
    false
  );
$$;

-- from 20251006145641_588803c2-0adc-4e93-800c-9ff0055e13ee.sql
-- Fix users table security vulnerabilities

-- Step 1: Create a secure function to get user profile WITHOUT mfa_secret
CREATE OR REPLACE FUNCTION public.get_user_profile(user_id uuid)
RETURNS TABLE (
  id uuid,
  practice_id uuid,
  auth_user_id uuid,
  role user_role,
  is_active boolean,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  is_practice_manager boolean,
  is_master_user boolean,
  mfa_enabled boolean,
  name text,
  email text,
  phone_number text
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT 
    id,
    practice_id,
    auth_user_id,
    role,
    is_active,
    created_at,
    updated_at,
    is_practice_manager,
    is_master_user,
    mfa_enabled,
    name,
    email,
    phone_number
  FROM public.users
  WHERE users.id = user_id OR users.auth_user_id = user_id;
$$;

-- from 20251006145641_588803c2-0adc-4e93-800c-9ff0055e13ee.sql
-- Step 7: Ensure practice managers can still view users in their practice
-- (Keep existing policy "Practice managers can view users in their practice")
-- This policy remains as-is for legitimate admin access

-- Step 8: Comment on security changes
COMMENT ON FUNCTION public.get_user_profile IS 'Secure function to retrieve user profiles without exposing mfa_secret. Use this function instead of direct SELECT queries.';

-- from 20251006150520_473f71cf-de51-4623-967f-cd16dda6ee5f.sql
-- Fix users table sensitive data exposure
-- Prevent mfa_secret from being readable and restrict access to phone numbers

-- Step 1: Update the existing get_user_profile function to NEVER return mfa_secret
-- This ensures even if someone calls the function, they can't get the MFA secret
DROP FUNCTION IF EXISTS public.get_user_profile(uuid);

-- from 20251006150520_473f71cf-de51-4623-967f-cd16dda6ee5f.sql
CREATE OR REPLACE FUNCTION public.get_user_profile(user_id uuid)
RETURNS TABLE(
  id uuid,
  practice_id uuid,
  auth_user_id uuid,
  role user_role,
  is_active boolean,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  is_practice_manager boolean,
  is_master_user boolean,
  mfa_enabled boolean,
  name text,
  email text,
  phone_number text
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = 'public'
AS $$
  SELECT 
    id,
    practice_id,
    auth_user_id,
    role,
    is_active,
    created_at,
    updated_at,
    is_practice_manager,
    is_master_user,
    mfa_enabled,
    name,
    email,
    phone_number
  FROM public.users
  WHERE users.id = user_id OR users.auth_user_id = user_id;
$$;

-- from 20251006150520_473f71cf-de51-4623-967f-cd16dda6ee5f.sql
-- Step 7: Create an audit trigger for mfa_secret access (optional but recommended)
-- This will help detect if anyone tries to access mfa_secret directly
CREATE OR REPLACE FUNCTION public.audit_mfa_secret_access()
RETURNS event_trigger
LANGUAGE plpgsql
AS $$
BEGIN
  -- This would log any attempts to select mfa_secret
  -- Implementation depends on your audit requirements
  RAISE NOTICE 'MFA secret access detected';
END;
$$;

-- from 20251006150603_0dc51c13-c9fb-42c2-87df-6f3f5abd3570.sql
-- Step 2: Remove the audit_mfa_secret_access function
-- It was not properly implemented and creates a linter warning
DROP FUNCTION IF EXISTS public.audit_mfa_secret_access() CASCADE;

-- from 20251006151343_a84ea524-1890-4942-aa4b-138a15712305.sql
-- 3. Create security definer function to check roles (prevents infinite recursion)
CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid, _role app_role)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.user_roles
    WHERE user_id = _user_id
      AND role = _role
  )
$$;

-- from 20251006151343_a84ea524-1890-4942-aa4b-138a15712305.sql
-- 4. Create helper function to get user's practice_id from user_roles
CREATE OR REPLACE FUNCTION public.get_user_practice_from_roles(_user_id uuid)
RETURNS uuid
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT practice_id
  FROM public.user_roles
  WHERE user_id = _user_id
  LIMIT 1
$$;

-- from 20251006151343_a84ea524-1890-4942-aa4b-138a15712305.sql
-- 9. Add audit trigger for role changes
CREATE OR REPLACE FUNCTION public.audit_role_changes()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO public.audit_logs (practice_id, user_id, entity_type, entity_id, action, after_data)
    VALUES (NEW.practice_id, auth.uid(), 'user_roles', NEW.id, 'INSERT', to_jsonb(NEW));
  ELSIF TG_OP = 'DELETE' THEN
    INSERT INTO public.audit_logs (practice_id, user_id, entity_type, entity_id, action, before_data)
    VALUES (OLD.practice_id, auth.uid(), 'user_roles', OLD.id, 'DELETE', to_jsonb(OLD));
  END IF;
  RETURN COALESCE(NEW, OLD);
END;
$$;

-- from 20251006151343_a84ea524-1890-4942-aa4b-138a15712305.sql
CREATE TRIGGER audit_user_role_changes
AFTER INSERT OR DELETE ON public.user_roles
FOR EACH ROW EXECUTE FUNCTION public.audit_role_changes();

-- from 20251006151343_a84ea524-1890-4942-aa4b-138a15712305.sql
COMMENT ON FUNCTION public.has_role IS 'SECURITY: Security definer function that safely checks user roles without triggering RLS recursion.';

-- from 20251006151343_a84ea524-1890-4942-aa4b-138a15712305.sql
-- 11. Update security definer functions
CREATE OR REPLACE FUNCTION public.is_practice_manager(user_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT has_role(user_id, 'practice_manager');
$$;

-- from 20251006151343_a84ea524-1890-4942-aa4b-138a15712305.sql
CREATE OR REPLACE FUNCTION public.is_current_user_practice_manager()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT has_role(auth.uid(), 'practice_manager');
$$;

-- from 20251006151715_a0f24965-9aee-4b87-8c45-8745ab1c0cea.sql
-- 6. Add audit logging for sensitive data access
CREATE OR REPLACE FUNCTION public.audit_sensitive_access()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Log when someone accesses sensitive candidate or user data
  IF TG_TABLE_NAME = 'candidates' THEN
    INSERT INTO public.audit_logs (
      practice_id, 
      user_id, 
      entity_type, 
      entity_id, 
      action, 
      after_data
    )
    VALUES (
      NEW.practice_id, 
      auth.uid(), 
      'candidates_access', 
      NEW.id, 
      'SELECT', 
      jsonb_build_object('email', NEW.email, 'name', NEW.name)
    );
  END IF;
  RETURN NEW;
END;
$$;

-- from 20251006151750_8f7d51ef-dd7c-47c3-b58f-34246ecc1647.sql
-- 5. Add additional security: Create function to check if field access is allowed
CREATE OR REPLACE FUNCTION public.can_access_sensitive_user_field(_target_user_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT 
    -- User accessing their own data
    _target_user_id = auth.uid()
    OR
    -- Master users can access all
    is_current_user_master();
$$;

-- from 20251006151750_8f7d51ef-dd7c-47c3-b58f-34246ecc1647.sql
COMMENT ON FUNCTION public.can_access_sensitive_user_field IS 'SECURITY: Checks if current user can access sensitive fields (mfa_secret, phone_number) for target user.';

-- from 20251006152728_b5c143e5-330d-4017-aa7e-c7c00f9a52b8.sql
-- 2. Keep INSERT and UPDATE policies for initial setup and changes
-- These are safe because users need to set their MFA secrets initially
-- The existing UPDATE and INSERT policies are fine and should remain

-- 3. Create a secure server-side function to verify MFA tokens
-- This allows validation without exposing the secret
CREATE OR REPLACE FUNCTION public.verify_user_mfa_token(
  _user_id uuid,
  _token text
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  stored_secret text;
BEGIN
  -- Only allow users to verify their own tokens
  IF NOT EXISTS (
    SELECT 1 FROM public.users 
    WHERE id = _user_id 
    AND auth_user_id = auth.uid()
  ) THEN
    RAISE EXCEPTION 'Unauthorized: Can only verify own MFA token';
  END IF;

  -- Get the MFA secret (this happens server-side with elevated privileges)
  SELECT mfa_secret INTO stored_secret
  FROM public.user_auth_sensitive
  WHERE user_id = _user_id;

  IF stored_secret IS NULL THEN
    RETURN false;
  END IF;

  -- TODO: Implement actual TOTP/HOTP verification here
  -- For now, this is a placeholder that should be replaced with proper
  -- TOTP verification logic (e.g., using a proper TOTP library)
  -- The secret should never leave this function
  
  -- Placeholder validation - replace with actual TOTP verification
  -- This would typically use a library like otp-auth or similar
  RETURN true; -- TEMPORARY: Replace with actual TOTP verification
  
END;
$$;

-- from 20251006152728_b5c143e5-330d-4017-aa7e-c7c00f9a52b8.sql
-- 4. Create a function to check if user has MFA enabled (without exposing secret)
CREATE OR REPLACE FUNCTION public.user_has_mfa_enabled(_user_id uuid)
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 
    FROM public.user_auth_sensitive 
    WHERE user_id = _user_id 
    AND mfa_secret IS NOT NULL
  );
$$;

-- from 20251006152728_b5c143e5-330d-4017-aa7e-c7c00f9a52b8.sql
COMMENT ON FUNCTION public.verify_user_mfa_token IS 
'Securely verifies MFA tokens without exposing secrets. 
Users can only verify their own tokens. 
Secrets never leave the database server.';

-- from 20251006152728_b5c143e5-330d-4017-aa7e-c7c00f9a52b8.sql
-- 6. Grant execute permission on the verification function
GRANT EXECUTE ON FUNCTION public.verify_user_mfa_token TO authenticated;

-- from 20251006152728_b5c143e5-330d-4017-aa7e-c7c00f9a52b8.sql
GRANT EXECUTE ON FUNCTION public.user_has_mfa_enabled TO authenticated;

-- from 20251006160335_f573e66b-13af-4dd5-9e6c-5212dfdfdb3f.sql
-- 4. Create a helper function to calculate next due date based on frequency and start date
CREATE OR REPLACE FUNCTION public.calculate_next_due_date(
  _start_date date,
  _frequency process_frequency,
  _occurrence_count integer DEFAULT 0
)
RETURNS timestamp with time zone
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
  next_date timestamp with time zone;
BEGIN
  next_date := _start_date::timestamp with time zone;
  
  CASE _frequency
    WHEN 'twice_daily' THEN
      -- For twice daily, alternate between morning (8am) and evening (8pm)
      IF _occurrence_count % 2 = 0 THEN
        next_date := next_date + ((_occurrence_count / 2) || ' days')::interval + '8 hours'::interval;
      ELSE
        next_date := next_date + ((_occurrence_count / 2) || ' days')::interval + '20 hours'::interval;
      END IF;
    WHEN 'daily' THEN
      next_date := next_date + (_occurrence_count || ' days')::interval;
    WHEN 'weekly' THEN
      next_date := next_date + ((_occurrence_count * 7) || ' days')::interval;
    WHEN 'monthly' THEN
      next_date := next_date + (_occurrence_count || ' months')::interval;
    WHEN 'quarterly' THEN
      next_date := next_date + ((_occurrence_count * 3) || ' months')::interval;
    WHEN 'annually' THEN
      next_date := next_date + (_occurrence_count || ' years')::interval;
    ELSE
      -- Default to weekly
      next_date := next_date + ((_occurrence_count * 7) || ' days')::interval;
  END CASE;
  
  RETURN next_date;
END;
$$;

-- from 20251006160335_f573e66b-13af-4dd5-9e6c-5212dfdfdb3f.sql
COMMENT ON FUNCTION public.calculate_next_due_date IS 
'Calculates the next due date for a process instance based on start date, frequency, and occurrence count';

-- from 20251006160335_f573e66b-13af-4dd5-9e6c-5212dfdfdb3f.sql
-- 5. Create a function to check compliance based on SLA
CREATE OR REPLACE FUNCTION public.is_task_compliant(
  _due_at timestamp with time zone,
  _completed_at timestamp with time zone,
  _sla_hours integer
)
RETURNS boolean
LANGUAGE sql
STABLE
AS $$
  SELECT CASE 
    WHEN _completed_at IS NULL THEN 
      -- Not yet completed, check if still within SLA window
      now() <= (_due_at + (_sla_hours || ' hours')::interval)
    ELSE
      -- Completed, check if it was within SLA
      _completed_at <= (_due_at + (_sla_hours || ' hours')::interval)
  END;
$$;

-- from 20251006160335_f573e66b-13af-4dd5-9e6c-5212dfdfdb3f.sql
COMMENT ON FUNCTION public.is_task_compliant IS 
'Checks if a task is compliant based on SLA hours. Returns true if completed within SLA or still within window.';

-- from 20251006160335_f573e66b-13af-4dd5-9e6c-5212dfdfdb3f.sql
-- 6. Grant execute permissions
GRANT EXECUTE ON FUNCTION public.calculate_next_due_date TO authenticated;

-- from 20251006160335_f573e66b-13af-4dd5-9e6c-5212dfdfdb3f.sql
GRANT EXECUTE ON FUNCTION public.is_task_compliant TO authenticated;

-- from 20251006160426_ded2e4f2-545a-4bb0-8f9b-fa08b67ad64e.sql
-- Fix search path for compliance function

DROP FUNCTION IF EXISTS public.is_task_compliant(timestamp with time zone, timestamp with time zone, integer);

-- from 20251006160426_ded2e4f2-545a-4bb0-8f9b-fa08b67ad64e.sql
CREATE OR REPLACE FUNCTION public.is_task_compliant(
  _due_at timestamp with time zone,
  _completed_at timestamp with time zone,
  _sla_hours integer
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT CASE 
    WHEN _completed_at IS NULL THEN 
      -- Not yet completed, check if still within SLA window
      now() <= (_due_at + (_sla_hours || ' hours')::interval)
    ELSE
      -- Completed, check if it was within SLA
      _completed_at <= (_due_at + (_sla_hours || ' hours')::interval)
  END;
$$;

-- from 20251006160426_ded2e4f2-545a-4bb0-8f9b-fa08b67ad64e.sql
COMMENT ON FUNCTION public.is_task_compliant IS 
'Checks if a task is compliant based on SLA hours. Returns true if completed within SLA or still within window.';

-- from 20251006160426_ded2e4f2-545a-4bb0-8f9b-fa08b67ad64e.sql
GRANT EXECUTE ON FUNCTION public.is_task_compliant TO authenticated;

-- from 20251006172350_984451c5-d9cd-4580-a61d-d26383581baa.sql
-- Fix search path and add security definer for calculate_next_due_date function

DROP FUNCTION IF EXISTS public.calculate_next_due_date(date, process_frequency, integer);

-- from 20251006172350_984451c5-d9cd-4580-a61d-d26383581baa.sql
CREATE OR REPLACE FUNCTION public.calculate_next_due_date(
  _start_date date,
  _frequency process_frequency,
  _occurrence_count integer DEFAULT 0
)
RETURNS timestamp with time zone
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  next_date timestamp with time zone;
BEGIN
  next_date := _start_date::timestamp with time zone;
  
  CASE _frequency
    WHEN 'twice_daily' THEN
      -- For twice daily, alternate between morning (8am) and evening (8pm)
      IF _occurrence_count % 2 = 0 THEN
        next_date := next_date + ((_occurrence_count / 2) || ' days')::interval + '8 hours'::interval;
      ELSE
        next_date := next_date + ((_occurrence_count / 2) || ' days')::interval + '20 hours'::interval;
      END IF;
    WHEN 'daily' THEN
      next_date := next_date + (_occurrence_count || ' days')::interval;
    WHEN 'weekly' THEN
      next_date := next_date + ((_occurrence_count * 7) || ' days')::interval;
    WHEN 'monthly' THEN
      next_date := next_date + (_occurrence_count || ' months')::interval;
    WHEN 'quarterly' THEN
      next_date := next_date + ((_occurrence_count * 3) || ' months')::interval;
    WHEN 'annually' THEN
      next_date := next_date + (_occurrence_count || ' years')::interval;
    ELSE
      -- Default to weekly
      next_date := next_date + ((_occurrence_count * 7) || ' days')::interval;
  END CASE;
  
  RETURN next_date;
END;
$$;

-- from 20251006172350_984451c5-d9cd-4580-a61d-d26383581baa.sql
COMMENT ON FUNCTION public.calculate_next_due_date IS 
'Calculates the next due date for a process instance based on start date, frequency, and occurrence count';

-- from 20251006172350_984451c5-d9cd-4580-a61d-d26383581baa.sql
GRANT EXECUTE ON FUNCTION public.calculate_next_due_date TO authenticated;

-- from 20251007093547_28374446-1f94-44cb-85b1-828bda78eb0c.sql
-- Add triggers for updated_at
CREATE TRIGGER update_country_profile_settings_updated_at
  BEFORE UPDATE ON public.country_profile_settings
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- from 20251007093547_28374446-1f94-44cb-85b1-828bda78eb0c.sql
CREATE TRIGGER update_practice_targets_updated_at
  BEFORE UPDATE ON public.practice_targets
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- from 20251007094800_363507ed-b801-4b34-8381-a256a8d3cc03.sql
-- Create security definer function to check if user is practice manager (without recursion)
CREATE OR REPLACE FUNCTION public.is_user_practice_manager_for_practice(_user_id uuid, _practice_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.users
    WHERE auth_user_id = _user_id
      AND practice_id = _practice_id
      AND is_practice_manager = true
  )
$$;

-- from 20251007094800_363507ed-b801-4b34-8381-a256a8d3cc03.sql
-- Grant execute on the new function
GRANT EXECUTE ON FUNCTION public.is_user_practice_manager_for_practice TO authenticated;

-- from 20251007101718_3791314d-1942-4026-8e3b-518b4495fb26.sql
-- Triggers for updated_at (using DROP IF EXISTS to avoid conflicts)
DROP TRIGGER IF EXISTS update_country_profile_settings_updated_at ON public.country_profile_settings;

-- from 20251007101718_3791314d-1942-4026-8e3b-518b4495fb26.sql
CREATE TRIGGER update_country_profile_settings_updated_at
  BEFORE UPDATE ON public.country_profile_settings
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- from 20251007101718_3791314d-1942-4026-8e3b-518b4495fb26.sql
DROP TRIGGER IF EXISTS update_practice_targets_updated_at ON public.practice_targets;

-- from 20251007101718_3791314d-1942-4026-8e3b-518b4495fb26.sql
CREATE TRIGGER update_practice_targets_updated_at
  BEFORE UPDATE ON public.practice_targets
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- from 20251110141524_84a71ba6-73b7-4404-808f-595d61292196.sql
-- ========================================
-- CRITICAL RLS POLICY FIX MIGRATION
-- Fix all policies referencing removed users.role column
-- Compliance: DSPT, HIW, CQC (Least-privilege RBAC)
-- ========================================

-- Phase 1: Create security definer function for role checking
-- This function checks if a user has ANY of the specified roles from user_roles table
CREATE OR REPLACE FUNCTION public.has_any_role(_user_id uuid, _roles app_role[])
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.user_roles
    WHERE user_id = _user_id
      AND role = ANY(_roles)
  )
$$;

-- from 20251110145552_3bcd2d15-8c19-458b-ba99-fe4efde1b8a8.sql
-- Function to auto-expire old notifications (cleanup)
CREATE OR REPLACE FUNCTION expire_old_notifications()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  DELETE FROM public.notifications
  WHERE expires_at < now();
END;
$$;

-- from 20251110145606_a7a5b087-af1e-4ccc-8909-c1f644700f50.sql
-- Fix search_path for expire_old_notifications function
DROP FUNCTION IF EXISTS expire_old_notifications();

-- from 20251110145606_a7a5b087-af1e-4ccc-8909-c1f644700f50.sql
CREATE OR REPLACE FUNCTION expire_old_notifications()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  DELETE FROM public.notifications
  WHERE expires_at < now();
END;
$$;

-- from 20251110155323_17f36d1c-9835-4758-9ae7-0ce886a8aa5e.sql
-- Create trigger for automatic timestamp updates
CREATE TRIGGER update_notification_preferences_updated_at
BEFORE UPDATE ON public.notification_preferences
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- from 20251110155323_17f36d1c-9835-4758-9ae7-0ce886a8aa5e.sql
-- Create function to get unacknowledged policies count for notifications
CREATE OR REPLACE FUNCTION public.get_unacknowledged_policies_count(p_user_id UUID)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_practice_id UUID;
  v_count INTEGER;
BEGIN
  -- Get user's practice
  SELECT practice_id INTO v_practice_id
  FROM users
  WHERE id = p_user_id;

  -- Count active policies not acknowledged by this user
  SELECT COUNT(*)::INTEGER INTO v_count
  FROM policy_documents pd
  WHERE pd.practice_id = v_practice_id
    AND pd.is_active = true
    AND NOT EXISTS (
      SELECT 1 
      FROM policy_acknowledgments pa
      WHERE pa.policy_id = pd.id
        AND pa.user_id = p_user_id
        AND pa.version = pd.version
    );

  RETURN COALESCE(v_count, 0);
END;
$$;

-- from 20251110162617_026266d3-c7c0-492f-a2ed-2a76c409f620.sql
-- Create updated_at trigger
CREATE TRIGGER update_email_logs_updated_at
  BEFORE UPDATE ON public.email_logs
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- from 20251110173503_84a0a7c2-1bdd-40d3-b911-94a4f05dded2.sql
-- Security Fix: Replace subquery patterns with security definer functions
-- This addresses two critical security findings:
-- 1. user_auth_sensitive_mfa_exposure
-- 2. users_table_public_exposure

-- Create security definer function to get user's internal ID from auth
CREATE OR REPLACE FUNCTION public.get_user_id_from_auth()
RETURNS uuid
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT id FROM users WHERE auth_user_id = auth.uid() LIMIT 1;
$$;

-- from 20251110173503_84a0a7c2-1bdd-40d3-b911-94a4f05dded2.sql
-- Create security definer function to check if user is in same practice
CREATE OR REPLACE FUNCTION public.is_in_same_practice(_user_id uuid, _target_user_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 
    FROM users u1
    JOIN users u2 ON u1.practice_id = u2.practice_id
    WHERE u1.id = _user_id 
      AND u2.id = _target_user_id
  );
$$;

-- from 20251110174829_141b62e4-58f2-41ce-aad9-f28f9b8221d2.sql
-- CRITICAL FIX 3: Audit MFA access
-- Create audit trigger to log when MFA data is accessed
CREATE OR REPLACE FUNCTION public.audit_mfa_access()
RETURNS TRIGGER AS $$
BEGIN
  -- Log when someone accesses MFA data (not their own)
  IF NOT (NEW.user_id = get_user_id_from_auth()) THEN
    INSERT INTO audit_logs (
      practice_id,
      user_id,
      entity_type,
      entity_id,
      action,
      after_data
    ) VALUES (
      (SELECT practice_id FROM users WHERE id = NEW.user_id),
      get_user_id_from_auth(),
      'mfa_access',
      NEW.user_id,
      TG_OP,
      jsonb_build_object(
        'accessed_user_id', NEW.user_id,
        'has_mfa_enabled', (NEW.mfa_secret IS NOT NULL),
        'timestamp', now()
      )
    );
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- from 20251110174829_141b62e4-58f2-41ce-aad9-f28f9b8221d2.sql
CREATE TRIGGER audit_mfa_sensitive_access
AFTER INSERT OR UPDATE ON user_auth_sensitive
FOR EACH ROW
EXECUTE FUNCTION audit_mfa_access();

-- from 20251110175311_d6365cae-cb91-4896-aed2-2254cfc826fb.sql
-- Add audit logging function for PII access
CREATE OR REPLACE FUNCTION public.audit_user_pii_access()
RETURNS TRIGGER AS $$
BEGIN
  -- Log when practice managers access full user records (with emails)
  IF NOT (NEW.auth_user_id = auth.uid()) AND is_current_user_practice_manager() THEN
    INSERT INTO audit_logs (
      practice_id,
      user_id,
      entity_type,
      entity_id,
      action,
      after_data
    ) VALUES (
      NEW.practice_id,
      get_user_id_from_auth(),
      'user_pii_access',
      NEW.id,
      'SELECT',
      jsonb_build_object(
        'accessed_user_name', NEW.name,
        'accessed_user_email', NEW.email,
        'timestamp', now()
      )
    );
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- from 20251110175311_d6365cae-cb91-4896-aed2-2254cfc826fb.sql
COMMENT ON FUNCTION public.audit_user_pii_access IS 
'Audit function to log when practice managers access user PII. Application code should use users_public_info view to avoid exposing emails.';

-- from 20251111141352_ca1c9670-ba42-41bf-8dca-eea4d59a250d.sql
-- Create audited function to get employee email
CREATE OR REPLACE FUNCTION public.get_employee_email_audited(_employee_id UUID)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  _email TEXT;
  _practice_id UUID;
BEGIN
  -- Only practice managers and master users can call this
  IF NOT (is_current_user_practice_manager() OR is_current_user_master()) THEN
    RAISE EXCEPTION 'Unauthorized: Only practice managers can access employee emails';
  END IF;

  -- Get the email
  SELECT email INTO _email
  FROM public.employee_contact_details
  WHERE employee_id = _employee_id;

  -- Get practice_id for audit log
  SELECT practice_id INTO _practice_id
  FROM public.employees
  WHERE id = _employee_id;

  -- Log the access
  INSERT INTO public.audit_logs (
    practice_id,
    user_id,
    entity_type,
    entity_id,
    action,
    after_data
  ) VALUES (
    _practice_id,
    get_user_id_from_auth(),
    'employee_email_access',
    _employee_id,
    'SELECT',
    jsonb_build_object(
      'accessed_employee_id', _employee_id,
      'timestamp', now()
    )
  );

  RETURN _email;
END;
$$;

-- from 20251111141352_ca1c9670-ba42-41bf-8dca-eea4d59a250d.sql
-- Add updated_at trigger for employee_contact_details
CREATE TRIGGER update_employee_contact_details_updated_at
  BEFORE UPDATE ON public.employee_contact_details
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- from 20251111141352_ca1c9670-ba42-41bf-8dca-eea4d59a250d.sql
-- Create audited function to get candidate email
CREATE OR REPLACE FUNCTION public.get_candidate_email_audited(_candidate_id UUID)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  _email TEXT;
  _practice_id UUID;
BEGIN
  -- Only practice managers and master users can call this
  IF NOT (is_current_user_practice_manager() OR is_current_user_master()) THEN
    RAISE EXCEPTION 'Unauthorized: Only practice managers can access candidate emails';
  END IF;

  -- Get the email
  SELECT email INTO _email
  FROM public.candidate_contact_details
  WHERE candidate_id = _candidate_id;

  -- Get practice_id for audit log
  SELECT practice_id INTO _practice_id
  FROM public.candidates
  WHERE id = _candidate_id;

  -- Log the access
  INSERT INTO public.audit_logs (
    practice_id,
    user_id,
    entity_type,
    entity_id,
    action,
    after_data
  ) VALUES (
    _practice_id,
    get_user_id_from_auth(),
    'candidate_email_access',
    _candidate_id,
    'SELECT',
    jsonb_build_object(
      'accessed_candidate_id', _candidate_id,
      'timestamp', now()
    )
  );

  RETURN _email;
END;
$$;

-- from 20251111141352_ca1c9670-ba42-41bf-8dca-eea4d59a250d.sql
-- Add updated_at trigger for candidate_contact_details
CREATE TRIGGER update_candidate_contact_details_updated_at
  BEFORE UPDATE ON public.candidate_contact_details
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- from 20251111141352_ca1c9670-ba42-41bf-8dca-eea4d59a250d.sql
-- Create audited function to get role assignment email
CREATE OR REPLACE FUNCTION public.get_role_assignment_email_audited(_assignment_id UUID)
RETURNS TEXT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  _email TEXT;
  _practice_id UUID;
BEGIN
  -- Only practice managers and master users can call this
  IF NOT (is_current_user_practice_manager() OR is_current_user_master()) THEN
    RAISE EXCEPTION 'Unauthorized: Only practice managers can access role assignment emails';
  END IF;

  -- Get the email
  SELECT assigned_email INTO _email
  FROM public.role_assignment_contacts
  WHERE assignment_id = _assignment_id;

  -- Get practice_id for audit log
  SELECT practice_id INTO _practice_id
  FROM public.role_assignments
  WHERE id = _assignment_id;

  -- Log the access
  INSERT INTO public.audit_logs (
    practice_id,
    user_id,
    entity_type,
    entity_id,
    action,
    after_data
  ) VALUES (
    _practice_id,
    get_user_id_from_auth(),
    'role_assignment_email_access',
    _assignment_id,
    'SELECT',
    jsonb_build_object(
      'accessed_assignment_id', _assignment_id,
      'timestamp', now()
    )
  );

  RETURN _email;
END;
$$;

-- from 20251111141352_ca1c9670-ba42-41bf-8dca-eea4d59a250d.sql
-- Add updated_at trigger for role_assignment_contacts
CREATE TRIGGER update_role_assignment_contacts_updated_at
  BEFORE UPDATE ON public.role_assignment_contacts
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- from 20251111142618_041f35d7-58e0-4a85-b003-2819a0bed980.sql
-- ============================================================================
-- 4. CREATE SECURITY DEFINER FUNCTIONS AS PROPER VIEW REPLACEMENTS
-- ============================================================================

-- Replace users_for_assignment view with a security definer function
CREATE OR REPLACE FUNCTION public.get_users_for_assignment()
RETURNS TABLE (
  id uuid,
  practice_id uuid,
  is_active boolean,
  role app_role,
  name text
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT 
    u.id,
    u.practice_id,
    u.is_active,
    ur.role,
    u.name
  FROM users u
  LEFT JOIN user_roles ur ON u.id = ur.user_id
  WHERE u.is_active = true
    AND (
      u.practice_id = get_current_user_practice_id()
      OR is_current_user_master()
    );
$$;

-- from 20251111142618_041f35d7-58e0-4a85-b003-2819a0bed980.sql
-- Replace users_public_info view with a security definer function
CREATE OR REPLACE FUNCTION public.get_users_public_info()
RETURNS TABLE (
  practice_id uuid,
  id uuid,
  is_active boolean,
  auth_user_id uuid,
  name text
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT 
    practice_id,
    id,
    is_active,
    auth_user_id,
    name
  FROM users
  WHERE practice_id = get_current_user_practice_id()
    OR is_current_user_master();
$$;

-- from 20251111142618_041f35d7-58e0-4a85-b003-2819a0bed980.sql
-- Replace user_mfa_status view with a security definer function
CREATE OR REPLACE FUNCTION public.get_user_mfa_status(target_user_id uuid DEFAULT NULL)
RETURNS TABLE (
  user_id uuid,
  mfa_enabled boolean,
  phone_configured boolean,
  updated_at timestamp with time zone
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT 
    uas.user_id,
    (uas.mfa_secret IS NOT NULL) as mfa_enabled,
    (uas.phone_number IS NOT NULL) as phone_configured,
    uas.updated_at
  FROM user_auth_sensitive uas
  WHERE (
    -- User viewing their own status
    (target_user_id IS NULL AND uas.user_id = get_user_id_from_auth())
    OR (target_user_id IS NOT NULL AND uas.user_id = target_user_id AND uas.user_id = get_user_id_from_auth())
    -- Practice manager viewing their practice users
    OR (
      is_current_user_practice_manager() 
      AND uas.user_id IN (
        SELECT id FROM users WHERE practice_id = get_current_user_practice_id()
      )
    )
    -- Master user viewing any user
    OR is_current_user_master()
  );
$$;

-- from 20251111151316_daac5351-a839-4b88-83a0-3cb9cdfddc7f.sql
-- ==========================================
-- 6. TRIGGERS
-- ==========================================

-- Update updated_at timestamp trigger for new tables
CREATE TRIGGER update_organization_setup_updated_at
  BEFORE UPDATE ON public.organization_setup
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- from 20251111151316_daac5351-a839-4b88-83a0-3cb9cdfddc7f.sql
CREATE TRIGGER update_scheduled_reminders_updated_at
  BEFORE UPDATE ON public.scheduled_reminders
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- from 20251111151316_daac5351-a839-4b88-83a0-3cb9cdfddc7f.sql
CREATE TRIGGER update_compliance_status_updated_at
  BEFORE UPDATE ON public.compliance_status
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- from 20251111153903_a63fbdeb-a7b6-4e7f-ba57-96fbbf44ebe7.sql
-- ============================================================================
-- 6. TRIGGERS FOR UPDATED_AT
-- ============================================================================

CREATE TRIGGER update_fire_assessments_updated_at
  BEFORE UPDATE ON public.fire_safety_assessments
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- from 20251111153903_a63fbdeb-a7b6-4e7f-ba57-96fbbf44ebe7.sql
CREATE TRIGGER update_fire_actions_updated_at
  BEFORE UPDATE ON public.fire_safety_actions
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- from 20251111153903_a63fbdeb-a7b6-4e7f-ba57-96fbbf44ebe7.sql
CREATE TRIGGER update_dbs_checks_updated_at
  BEFORE UPDATE ON public.dbs_checks
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- from 20251111153903_a63fbdeb-a7b6-4e7f-ba57-96fbbf44ebe7.sql
-- ============================================================================
-- 7. NOTIFICATION TRIGGERS
-- ============================================================================

-- Trigger to notify estates lead when critical fire safety action is created
CREATE OR REPLACE FUNCTION public.notify_critical_fire_action()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.severity IN ('high', 'critical') THEN
    INSERT INTO public.notifications (
      practice_id,
      user_id,
      notification_type,
      priority,
      title,
      message,
      action_url
    )
    SELECT 
      NEW.practice_id,
      u.id,
      'fire_safety_action',
      CASE NEW.severity
        WHEN 'critical' THEN 'urgent'
        WHEN 'high' THEN 'high'
        ELSE 'medium'
      END,
      'Critical Fire Safety Action Required',
      'A ' || NEW.severity || ' priority fire safety action has been created: ' || NEW.action_description,
      '/fire-safety'
    FROM public.users u
    INNER JOIN public.user_roles ur ON u.id = ur.user_id
    WHERE u.practice_id = NEW.practice_id
      AND ur.role IN ('estates_lead', 'practice_manager')
      AND u.is_active = true;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- from 20251111153903_a63fbdeb-a7b6-4e7f-ba57-96fbbf44ebe7.sql
CREATE TRIGGER fire_action_notification
  AFTER INSERT ON public.fire_safety_actions
  FOR EACH ROW EXECUTE FUNCTION public.notify_critical_fire_action();

-- from 20251124174349_faae8e45-1187-4743-bf8d-cac44f3fb229.sql
-- Now fix orphaned auth users
CREATE OR REPLACE FUNCTION fix_orphaned_auth_users()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_practice_id uuid := '538f42bf-b7f0-493b-992c-0952b80932f3';
  v_user_record record;
  v_new_user_id uuid;
BEGIN
  FOR v_user_record IN 
    SELECT au.id as auth_id, au.email
    FROM auth.users au
    WHERE NOT EXISTS (SELECT 1 FROM users WHERE auth_user_id = au.id)
  LOOP
    INSERT INTO users (auth_user_id, practice_id, name, is_active, is_practice_manager, is_master_user)
    VALUES (v_user_record.auth_id, v_practice_id, split_part(v_user_record.email, '@', 1), true, true, false)
    RETURNING id INTO v_new_user_id;
    
    INSERT INTO user_roles (user_id, role, practice_id, created_by)
    VALUES (v_new_user_id, 'practice_manager', v_practice_id, v_new_user_id);
    
    INSERT INTO user_contact_details (user_id, email)
    VALUES (v_new_user_id, v_user_record.email);
  END LOOP;
  
  UPDATE practices SET onboarding_stage = 'live' WHERE id = v_practice_id;
END;
$$;

-- from 20251124174349_faae8e45-1187-4743-bf8d-cac44f3fb229.sql
DROP FUNCTION fix_orphaned_auth_users();

-- from 20251128124929_79984258-831f-4fcb-a9cc-ace2000f9c53.sql
-- Fix is_current_user_practice_manager() to use get_user_id_from_auth()
-- This resolves auth.uid() -> users.id before calling has_role()

CREATE OR REPLACE FUNCTION public.is_current_user_practice_manager()
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT has_role(get_user_id_from_auth(), 'practice_manager');
$function$;

-- from 20251218162641_54831192-df26-413f-89e8-f396c7310c0b.sql
-- Create trigger for auto-creating employee records for new users
CREATE OR REPLACE FUNCTION create_employee_for_new_user()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.practice_id IS NOT NULL THEN
    INSERT INTO employees (practice_id, user_id, name, start_date)
    VALUES (NEW.practice_id, NEW.id, NEW.name, CURRENT_DATE);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- from 20251218162641_54831192-df26-413f-89e8-f396c7310c0b.sql
-- Drop trigger if exists and recreate
DROP TRIGGER IF EXISTS on_user_created_create_employee ON users;

-- from 20251218162641_54831192-df26-413f-89e8-f396c7310c0b.sql
CREATE TRIGGER on_user_created_create_employee
AFTER INSERT ON users
FOR EACH ROW
EXECUTE FUNCTION create_employee_for_new_user();

-- from 20251218180925_22954729-c171-400b-baf9-dd2b9557e99d.sql
-- 4) Trigger: copy template audit fields onto task at creation
CREATE OR REPLACE FUNCTION public.apply_task_template_audit_fields()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  t public.task_templates;
BEGIN
  IF NEW.template_id IS NULL THEN
    RETURN NEW;
  END IF;

  SELECT * INTO t FROM public.task_templates WHERE id = NEW.template_id;

  IF FOUND THEN
    NEW.is_auditable := COALESCE(t.is_auditable, false);
    NEW.audit_frameworks := COALESCE(t.audit_frameworks, '{}'::text[]);
    NEW.evidence_min_count := COALESCE(t.evidence_min_count, 0);
    NEW.fit_for_audit_weight := COALESCE(t.fit_for_audit_weight, 1);
  END IF;

  RETURN NEW;
END;
$$;

-- from 20251218180925_22954729-c171-400b-baf9-dd2b9557e99d.sql
DROP TRIGGER IF EXISTS trg_apply_task_template_audit_fields ON public.tasks;

-- from 20251218180925_22954729-c171-400b-baf9-dd2b9557e99d.sql
CREATE TRIGGER trg_apply_task_template_audit_fields
BEFORE INSERT OR UPDATE OF template_id ON public.tasks
FOR EACH ROW EXECUTE FUNCTION public.apply_task_template_audit_fields();

-- from 20251218180925_22954729-c171-400b-baf9-dd2b9557e99d.sql
-- 8) Trigger to log task changes into task_events
CREATE OR REPLACE FUNCTION public.log_task_changes()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  actor uuid;
BEGIN
  actor := public.get_user_id_from_auth();

  IF TG_OP = 'INSERT' THEN
    INSERT INTO public.task_events(practice_id, task_id, actor_user_id, event_type, after)
    VALUES (NEW.practice_id, NEW.id, actor, 'CREATED', jsonb_build_object('title', NEW.title, 'status', NEW.status, 'due_at', NEW.due_at));
    RETURN NEW;
  END IF;

  -- Status change
  IF (OLD.status IS DISTINCT FROM NEW.status) THEN
    INSERT INTO public.task_events(practice_id, task_id, actor_user_id, event_type, before, after)
    VALUES (NEW.practice_id, NEW.id, actor, 'STATUS_CHANGED', jsonb_build_object('status', OLD.status), jsonb_build_object('status', NEW.status));
  END IF;

  -- Due date change
  IF (OLD.due_at IS DISTINCT FROM NEW.due_at) THEN
    INSERT INTO public.task_events(practice_id, task_id, actor_user_id, event_type, before, after)
    VALUES (NEW.practice_id, NEW.id, actor, 'DUE_DATE_CHANGED', jsonb_build_object('due_at', OLD.due_at), jsonb_build_object('due_at', NEW.due_at));
  END IF;

  -- Assignment change
  IF (OLD.assigned_to_user_id IS DISTINCT FROM NEW.assigned_to_user_id) OR (OLD.assigned_to_role IS DISTINCT FROM NEW.assigned_to_role) THEN
    INSERT INTO public.task_events(practice_id, task_id, actor_user_id, event_type, before, after)
    VALUES (
      NEW.practice_id, NEW.id, actor, 'ASSIGNED',
      jsonb_build_object('assigned_to_user_id', OLD.assigned_to_user_id, 'assigned_to_role', OLD.assigned_to_role),
      jsonb_build_object('assigned_to_user_id', NEW.assigned_to_user_id, 'assigned_to_role', NEW.assigned_to_role)
    );
  END IF;

  RETURN NEW;
END;
$$;

-- from 20251218180925_22954729-c171-400b-baf9-dd2b9557e99d.sql
DROP TRIGGER IF EXISTS trg_log_task_changes ON public.tasks;

-- from 20251218180925_22954729-c171-400b-baf9-dd2b9557e99d.sql
CREATE TRIGGER trg_log_task_changes
AFTER INSERT OR UPDATE ON public.tasks
FOR EACH ROW EXECUTE FUNCTION public.log_task_changes();

-- from 20251218180925_22954729-c171-400b-baf9-dd2b9557e99d.sql
-- 9) Search RPC (secure: derives practice from auth)
CREATE OR REPLACE FUNCTION public.search_tasks_secure(
  p_query text DEFAULT '',
  p_module text DEFAULT NULL,
  p_status text DEFAULT NULL,
  p_priority text DEFAULT NULL,
  p_only_my_tasks boolean DEFAULT false,
  p_limit integer DEFAULT 50,
  p_offset integer DEFAULT 0
)
RETURNS TABLE (
  id uuid,
  title text,
  description text,
  module text,
  status text,
  priority text,
  due_at timestamptz,
  completed_at timestamptz,
  assigned_to_user_id uuid,
  assigned_to_role public.user_role,
  is_auditable boolean,
  evidence_min_count integer,
  evidence_count integer,
  rank real
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_practice_id uuid := public.get_current_user_practice_id();
  v_user_id uuid := public.get_user_id_from_auth();
  q tsquery;
BEGIN
  IF v_practice_id IS NULL THEN
    RAISE EXCEPTION 'No practice for user';
  END IF;

  IF coalesce(p_query,'') = '' THEN
    q := NULL;
  ELSE
    q := websearch_to_tsquery('english', p_query);
  END IF;

  RETURN QUERY
  SELECT
    t.id, t.title, t.description, t.module, t.status, t.priority, t.due_at, t.completed_at,
    t.assigned_to_user_id, t.assigned_to_role, t.is_auditable, t.evidence_min_count,
    (SELECT count(*)::int FROM public.evidence_v2 e WHERE e.task_id = t.id) AS evidence_count,
    CASE WHEN q IS NULL THEN NULL ELSE ts_rank_cd(t.search_vector, q) END AS rank
  FROM public.tasks t
  WHERE t.practice_id = v_practice_id
    AND (q IS NULL OR t.search_vector @@ q)
    AND (p_module IS NULL OR p_module = 'all' OR t.module = p_module)
    AND (p_status IS NULL OR p_status = 'all' OR t.status = p_status)
    AND (p_priority IS NULL OR p_priority = 'all' OR t.priority = p_priority)
    AND (NOT p_only_my_tasks OR t.assigned_to_user_id = v_user_id)
  ORDER BY rank DESC NULLS LAST, t.due_at ASC
  LIMIT p_limit OFFSET p_offset;
END;
$$;

-- from 20251218180925_22954729-c171-400b-baf9-dd2b9557e99d.sql
GRANT EXECUTE ON FUNCTION public.search_tasks_secure TO authenticated;

-- from 20251218180925_22954729-c171-400b-baf9-dd2b9557e99d.sql
-- 10) Scoring RPC (secure + performant)
CREATE OR REPLACE FUNCTION public.get_practice_scores_secure(
  p_practice_id uuid,
  p_start_date date DEFAULT NULL,
  p_end_date date DEFAULT NULL,
  p_as_of timestamptz DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_as_of timestamptz := COALESCE(p_as_of, now());
  v_start timestamptz;
  v_end timestamptz;
  total_due int;
  completed_on_time int;
  completed_late int;
  incomplete_due int;

  aud_total_due int;
  aud_pass int;

  compliance_score numeric;
  fit_score numeric;
BEGIN
  -- Authorize: caller must be in same practice as p_practice_id
  IF public.get_current_user_practice_id() IS NULL OR public.get_current_user_practice_id() <> p_practice_id THEN
    RAISE EXCEPTION 'Unauthorized practice';
  END IF;

  IF p_start_date IS NULL THEN
    v_start := (v_as_of - interval '30 days');
  ELSE
    v_start := p_start_date::timestamptz;
  END IF;

  IF p_end_date IS NULL THEN
    v_end := v_as_of;
  ELSE
    v_end := (p_end_date::timestamptz + interval '1 day') - interval '1 second';
  END IF;

  -- Compliance window: tasks with due_at in [v_start, v_end] and due_at <= as_of
  SELECT count(*) INTO total_due
  FROM public.tasks
  WHERE practice_id = p_practice_id
    AND due_at >= v_start AND due_at <= v_end
    AND due_at <= v_as_of;

  SELECT count(*) INTO completed_on_time
  FROM public.tasks
  WHERE practice_id = p_practice_id
    AND due_at >= v_start AND due_at <= v_end
    AND due_at <= v_as_of
    AND status = 'closed'
    AND completed_at IS NOT NULL
    AND completed_at <= due_at;

  SELECT count(*) INTO completed_late
  FROM public.tasks
  WHERE practice_id = p_practice_id
    AND due_at >= v_start AND due_at <= v_end
    AND due_at <= v_as_of
    AND status = 'closed'
    AND completed_at IS NOT NULL
    AND completed_at > due_at;

  SELECT count(*) INTO incomplete_due
  FROM public.tasks
  WHERE practice_id = p_practice_id
    AND due_at >= v_start AND due_at <= v_end
    AND due_at <= v_as_of
    AND status <> 'closed';

  -- Compliance scoring: on-time = 1.0, late = 0.7, incomplete = 0.0
  IF total_due = 0 THEN
    compliance_score := 100;
  ELSE
    compliance_score := round(((completed_on_time * 1.0 + completed_late * 0.7) / total_due) * 100, 2);
  END IF;

  -- Fit-for-audit: auditable tasks due up to as_of
  SELECT count(*) INTO aud_total_due
  FROM public.tasks
  WHERE practice_id = p_practice_id
    AND is_auditable = true
    AND due_at <= v_as_of
    AND (p_start_date IS NULL OR due_at >= v_start)
    AND (p_end_date IS NULL OR due_at <= v_end);

  SELECT count(*) INTO aud_pass
  FROM public.tasks t
  WHERE t.practice_id = p_practice_id
    AND t.is_auditable = true
    AND t.due_at <= v_as_of
    AND (p_start_date IS NULL OR t.due_at >= v_start)
    AND (p_end_date IS NULL OR t.due_at <= v_end)
    AND t.status = 'closed'
    AND (SELECT count(*) FROM public.evidence_v2 e WHERE e.task_id = t.id) >= t.evidence_min_count;

  IF aud_total_due = 0 THEN
    fit_score := 100;
  ELSE
    fit_score := round((aud_pass::numeric / aud_total_due::numeric) * 100, 2);
  END IF;

  RETURN jsonb_build_object(
    'asOf', v_as_of,
    'window', jsonb_build_object('start', v_start, 'end', v_end),
    'compliance', jsonb_build_object(
      'score', compliance_score,
      'totalDue', total_due,
      'completedOnTime', completed_on_time,
      'completedLate', completed_late,
      'incompleteDue', incomplete_due
    ),
    'fitForAudit', jsonb_build_object(
      'score', fit_score,
      'auditableDue', aud_total_due,
      'auditablePass', aud_pass
    )
  );
END;
$$;

-- from 20251218180925_22954729-c171-400b-baf9-dd2b9557e99d.sql
GRANT EXECUTE ON FUNCTION public.get_practice_scores_secure TO authenticated;

-- from 20251218184049_6cdfd992-f6b9-4cd1-9e0f-c323afa51d0d.sql
-- Fix search_path for database functions to prevent schema injection attacks

-- These functions already have search_path set, but let's ensure they're all consistent
-- and add it to any that might be missing it

-- Update search_tasks_secure
ALTER FUNCTION public.search_tasks_secure(text, text, text, text, boolean, integer, integer) 
SET search_path = public;

-- from 20251218184049_6cdfd992-f6b9-4cd1-9e0f-c323afa51d0d.sql
-- Update get_practice_scores_secure
ALTER FUNCTION public.get_practice_scores_secure(uuid, date, date, timestamp with time zone) 
SET search_path = public;

-- from 20251218184049_6cdfd992-f6b9-4cd1-9e0f-c323afa51d0d.sql
-- Update get_current_user_practice_id
ALTER FUNCTION public.get_current_user_practice_id() 
SET search_path = public;

-- from 20251218184049_6cdfd992-f6b9-4cd1-9e0f-c323afa51d0d.sql
-- Update get_user_id_from_auth
ALTER FUNCTION public.get_user_id_from_auth() 
SET search_path = public;

-- from 20251218184049_6cdfd992-f6b9-4cd1-9e0f-c323afa51d0d.sql
-- Update is_current_user_practice_manager
ALTER FUNCTION public.is_current_user_practice_manager() 
SET search_path = public;

-- from 20251218184049_6cdfd992-f6b9-4cd1-9e0f-c323afa51d0d.sql
-- Update is_current_user_master
ALTER FUNCTION public.is_current_user_master() 
SET search_path = public;

-- from 20251218184049_6cdfd992-f6b9-4cd1-9e0f-c323afa51d0d.sql
-- Update has_role
ALTER FUNCTION public.has_role(uuid, app_role) 
SET search_path = public;

-- from 20251218184049_6cdfd992-f6b9-4cd1-9e0f-c323afa51d0d.sql
-- Update has_any_role
ALTER FUNCTION public.has_any_role(uuid, app_role[]) 
SET search_path = public;

-- from 20251218184049_6cdfd992-f6b9-4cd1-9e0f-c323afa51d0d.sql
-- Update additional helper functions that may be missing search_path
ALTER FUNCTION public.get_user_practice_id(uuid) 
SET search_path = public;

-- from 20251218184049_6cdfd992-f6b9-4cd1-9e0f-c323afa51d0d.sql
ALTER FUNCTION public.get_user_practice_from_roles(uuid) 
SET search_path = public;

-- from 20251218184049_6cdfd992-f6b9-4cd1-9e0f-c323afa51d0d.sql
ALTER FUNCTION public.is_master_user(uuid) 
SET search_path = public;

-- from 20251218184049_6cdfd992-f6b9-4cd1-9e0f-c323afa51d0d.sql
ALTER FUNCTION public.is_practice_manager(uuid) 
SET search_path = public;

-- from 20251218184049_6cdfd992-f6b9-4cd1-9e0f-c323afa51d0d.sql
ALTER FUNCTION public.is_group_manager(uuid) 
SET search_path = public;

-- from 20251218184049_6cdfd992-f6b9-4cd1-9e0f-c323afa51d0d.sql
ALTER FUNCTION public.is_in_same_practice(uuid, uuid) 
SET search_path = public;

-- from 20251218184049_6cdfd992-f6b9-4cd1-9e0f-c323afa51d0d.sql
ALTER FUNCTION public.is_user_practice_manager_for_practice(uuid, uuid) 
SET search_path = public;

-- from 20251218184049_6cdfd992-f6b9-4cd1-9e0f-c323afa51d0d.sql
ALTER FUNCTION public.can_access_sensitive_user_field(uuid) 
SET search_path = public;

-- from 20251218184049_6cdfd992-f6b9-4cd1-9e0f-c323afa51d0d.sql
ALTER FUNCTION public.is_task_compliant(timestamp with time zone, timestamp with time zone, integer) 
SET search_path = public;

-- from 20251218184049_6cdfd992-f6b9-4cd1-9e0f-c323afa51d0d.sql
ALTER FUNCTION public.calculate_next_due_date(date, process_frequency, integer) 
SET search_path = public;

-- from 20251218184049_6cdfd992-f6b9-4cd1-9e0f-c323afa51d0d.sql
ALTER FUNCTION public.calculate_working_days(date, date) 
SET search_path = public;

-- from 20251218184049_6cdfd992-f6b9-4cd1-9e0f-c323afa51d0d.sql
ALTER FUNCTION public.add_working_days(date, integer) 
SET search_path = public;

-- from 20251218184049_6cdfd992-f6b9-4cd1-9e0f-c323afa51d0d.sql
ALTER FUNCTION public.get_unacknowledged_policies_count(uuid) 
SET search_path = public;

-- from 20251218184049_6cdfd992-f6b9-4cd1-9e0f-c323afa51d0d.sql
ALTER FUNCTION public.expire_old_notifications() 
SET search_path = public;

-- from 20251218184355_3e65b4df-c1f7-41a7-82e1-3ab21514a8f1.sql
-- Fix search_path for trigger functions to prevent schema injection

-- set_cleaning_log_retention
CREATE OR REPLACE FUNCTION public.set_cleaning_log_retention()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path = public
AS $function$
BEGIN
  IF NEW.log_date IS NOT NULL AND NEW.retained_until IS NULL THEN
    NEW.retained_until := (NEW.log_date::DATE + INTERVAL '5 years')::TIMESTAMPTZ;
  END IF;
  RETURN NEW;
END;
$function$;

-- from 20251218184355_3e65b4df-c1f7-41a7-82e1-3ab21514a8f1.sql
-- set_complaint_sla_dates
CREATE OR REPLACE FUNCTION public.set_complaint_sla_dates()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path = public
AS $function$
BEGIN
  -- Set acknowledgment due date (2 working days)
  IF NEW.date_received IS NOT NULL AND NEW.acknowledgment_due_date IS NULL THEN
    NEW.acknowledgment_due_date := public.add_working_days(NEW.date_received::DATE, 2);
  END IF;
  
  -- Set final response due date (30 working days)
  IF NEW.date_received IS NOT NULL AND NEW.final_response_due_date IS NULL THEN
    NEW.final_response_due_date := public.add_working_days(NEW.date_received::DATE, 30);
  END IF;
  
  RETURN NEW;
END;
$function$;

-- from 20251218184355_3e65b4df-c1f7-41a7-82e1-3ab21514a8f1.sql
-- set_coshh_next_review
CREATE OR REPLACE FUNCTION public.set_coshh_next_review()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path = public
AS $function$
BEGIN
  IF NEW.next_review_date IS NULL THEN
    NEW.next_review_date := (NEW.created_at::DATE + INTERVAL '1 year')::DATE;
  END IF;
  RETURN NEW;
END;
$function$;

-- from 20251218184355_3e65b4df-c1f7-41a7-82e1-3ab21514a8f1.sql
-- set_fra_next_review
CREATE OR REPLACE FUNCTION public.set_fra_next_review()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path = public
AS $function$
BEGIN
  IF NEW.assessment_date IS NOT NULL AND NEW.next_review_date IS NULL THEN
    NEW.next_review_date := NEW.assessment_date + INTERVAL '1 year';
  END IF;
  RETURN NEW;
END;
$function$;

-- from 20251218184355_3e65b4df-c1f7-41a7-82e1-3ab21514a8f1.sql
-- set_ipc_audit_retention
CREATE OR REPLACE FUNCTION public.set_ipc_audit_retention()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path = public
AS $function$
BEGIN
  IF NEW.completed_at IS NOT NULL AND NEW.retained_until IS NULL THEN
    NEW.retained_until := NEW.completed_at + INTERVAL '5 years';
  END IF;
  RETURN NEW;
END;
$function$;

-- from 20251218184355_3e65b4df-c1f7-41a7-82e1-3ab21514a8f1.sql
-- set_risk_next_review
CREATE OR REPLACE FUNCTION public.set_risk_next_review()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path = public
AS $function$
BEGIN
  IF NEW.next_review_date IS NULL THEN
    NEW.next_review_date := (NEW.created_at::DATE + INTERVAL '1 year')::DATE;
  END IF;
  RETURN NEW;
END;
$function$;

-- from 20251218184355_3e65b4df-c1f7-41a7-82e1-3ab21514a8f1.sql
-- set_room_assessment_next_due
CREATE OR REPLACE FUNCTION public.set_room_assessment_next_due()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path = public
AS $function$
BEGIN
  IF NEW.assessment_date IS NOT NULL AND NEW.next_due_date IS NULL THEN
    NEW.next_due_date := NEW.assessment_date + INTERVAL '1 year';
  END IF;
  RETURN NEW;
END;
$function$;

-- from 20251218195648_511e2dd2-b7a6-451d-a97d-627064b5fb6f.sql
-- Create trigger for automatic timestamp updates
CREATE TRIGGER update_governance_approvals_updated_at
BEFORE UPDATE ON public.governance_approvals
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- from 20251219141327_23f138c0-27c6-419e-a368-89108695777a.sql
-- Helper function: Get current user's practice_id
CREATE OR REPLACE FUNCTION public.current_practice_id()
RETURNS uuid
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT u.practice_id FROM public.users u WHERE u.auth_user_id = auth.uid()
$$;

-- from 20251219141327_23f138c0-27c6-419e-a368-89108695777a.sql
-- Helper function: Check if current user has a specific capability
CREATE OR REPLACE FUNCTION public.has_capability(cap public.capability, p_id uuid DEFAULT NULL)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.user_practice_roles upr
    JOIN public.practice_roles pr ON pr.id = upr.practice_role_id
    JOIN public.role_catalog rc ON rc.id = pr.role_catalog_id
    LEFT JOIN public.practice_role_capabilities prc ON prc.practice_role_id = pr.id AND prc.capability = cap
    WHERE upr.user_id = (SELECT id FROM public.users WHERE auth_user_id = auth.uid())
      AND pr.practice_id = COALESCE(p_id, public.current_practice_id())
      AND pr.is_active = true
      AND (prc.capability IS NOT NULL OR cap = ANY(rc.default_capabilities))
  );
$$;

-- from 20251219141327_23f138c0-27c6-419e-a368-89108695777a.sql
-- Helper function: Get all capabilities for current user
CREATE OR REPLACE FUNCTION public.get_user_capabilities(p_id uuid DEFAULT NULL)
RETURNS public.capability[]
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT ARRAY_AGG(DISTINCT cap)
  FROM (
    SELECT unnest(rc.default_capabilities) AS cap
    FROM public.user_practice_roles upr
    JOIN public.practice_roles pr ON pr.id = upr.practice_role_id
    JOIN public.role_catalog rc ON rc.id = pr.role_catalog_id
    WHERE upr.user_id = (SELECT id FROM public.users WHERE auth_user_id = auth.uid())
      AND pr.practice_id = COALESCE(p_id, public.current_practice_id())
      AND pr.is_active = true
    UNION
    SELECT prc.capability
    FROM public.user_practice_roles upr
    JOIN public.practice_roles pr ON pr.id = upr.practice_role_id
    JOIN public.practice_role_capabilities prc ON prc.practice_role_id = pr.id
    WHERE upr.user_id = (SELECT id FROM public.users WHERE auth_user_id = auth.uid())
      AND pr.practice_id = COALESCE(p_id, public.current_practice_id())
      AND pr.is_active = true
  ) sub;
$$;

-- from 20251219154052_bc07e305-7902-4419-9ff7-2d8485118ee8.sql
-- Create has_capability function that checks user capabilities through new role system
-- with fallback to is_practice_manager for backward compatibility
CREATE OR REPLACE FUNCTION public.has_capability(_user_id uuid, _capability capability)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT 
    -- Fallback: is_practice_manager flag grants all capabilities (temporary)
    EXISTS (
      SELECT 1 FROM users 
      WHERE auth_user_id = _user_id 
      AND is_practice_manager = true
    )
    OR
    -- Master users have all capabilities
    EXISTS (
      SELECT 1 FROM users 
      WHERE auth_user_id = _user_id 
      AND is_master_user = true
    )
    OR
    -- Check role_catalog default_capabilities
    EXISTS (
      SELECT 1
      FROM user_practice_roles upr
      JOIN users u ON u.id = upr.user_id
      JOIN practice_roles pr ON pr.id = upr.practice_role_id
      JOIN role_catalog rc ON rc.id = pr.role_catalog_id
      WHERE u.auth_user_id = _user_id
        AND pr.is_active = true
        AND _capability = ANY(rc.default_capabilities)
    )
    OR
    -- Check practice_role_capabilities overrides
    EXISTS (
      SELECT 1
      FROM user_practice_roles upr
      JOIN users u ON u.id = upr.user_id
      JOIN practice_roles pr ON pr.id = upr.practice_role_id
      JOIN practice_role_capabilities prc ON prc.practice_role_id = pr.id
      WHERE u.auth_user_id = _user_id
        AND pr.is_active = true
        AND prc.capability = _capability
    )
$$;

-- from 20251219154052_bc07e305-7902-4419-9ff7-2d8485118ee8.sql
-- Convenience function for current authenticated user
CREATE OR REPLACE FUNCTION public.current_user_has_capability(_capability capability)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT public.has_capability(auth.uid(), _capability)
$$;

-- from 20251219154052_bc07e305-7902-4419-9ff7-2d8485118ee8.sql
-- Practice-scoped capability check for multi-practice scenarios
CREATE OR REPLACE FUNCTION public.has_capability_for_practice(
  _user_id uuid, 
  _capability capability, 
  _practice_id uuid
)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT 
    -- Fallback: is_practice_manager for the same practice
    EXISTS (
      SELECT 1 FROM users 
      WHERE auth_user_id = _user_id 
      AND practice_id = _practice_id
      AND is_practice_manager = true
    )
    OR
    -- Master users have all capabilities
    EXISTS (
      SELECT 1 FROM users 
      WHERE auth_user_id = _user_id 
      AND is_master_user = true
    )
    OR
    -- Role-based capability for specific practice
    EXISTS (
      SELECT 1
      FROM user_practice_roles upr
      JOIN users u ON u.id = upr.user_id
      JOIN practice_roles pr ON pr.id = upr.practice_role_id
      JOIN role_catalog rc ON rc.id = pr.role_catalog_id
      WHERE u.auth_user_id = _user_id
        AND pr.practice_id = _practice_id
        AND pr.is_active = true
        AND _capability = ANY(rc.default_capabilities)
    )
    OR
    -- Override capabilities for specific practice
    EXISTS (
      SELECT 1
      FROM user_practice_roles upr
      JOIN users u ON u.id = upr.user_id
      JOIN practice_roles pr ON pr.id = upr.practice_role_id
      JOIN practice_role_capabilities prc ON prc.practice_role_id = pr.id
      WHERE u.auth_user_id = _user_id
        AND pr.practice_id = _practice_id
        AND pr.is_active = true
        AND prc.capability = _capability
    )
$$;

-- from 20251219154052_bc07e305-7902-4419-9ff7-2d8485118ee8.sql
-- Add comments for documentation
COMMENT ON FUNCTION public.has_capability(_user_id uuid, _capability capability) IS 
'Checks if a user has a specific capability through the role system. Falls back to is_practice_manager flag for backward compatibility.';

-- from 20251219154052_bc07e305-7902-4419-9ff7-2d8485118ee8.sql
COMMENT ON FUNCTION public.current_user_has_capability(_capability capability) IS 
'Convenience function to check if the current authenticated user has a capability.';

-- from 20251219154052_bc07e305-7902-4419-9ff7-2d8485118ee8.sql
COMMENT ON FUNCTION public.has_capability_for_practice(_user_id uuid, _capability capability, _practice_id uuid) IS 
'Checks if a user has a specific capability within a specific practice.';

-- from 20251219155907_6581cef8-67e1-4f28-ab61-f8aef21ee3e4.sql
-- Update is_practice_manager() function to use new role system with fallback
CREATE OR REPLACE FUNCTION public.is_practice_manager(user_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = 'public'
AS $$
  SELECT 
    -- Fallback: Check is_practice_manager flag on users table
    EXISTS (
      SELECT 1 FROM users 
      WHERE auth_user_id = user_id 
      AND is_practice_manager = true
    )
    OR
    -- New role system: Check user_practice_roles for practice_manager role
    EXISTS (
      SELECT 1
      FROM user_practice_roles upr
      JOIN users u ON u.id = upr.user_id
      JOIN practice_roles pr ON pr.id = upr.practice_role_id
      JOIN role_catalog rc ON rc.id = pr.role_catalog_id
      WHERE u.auth_user_id = user_id
        AND pr.is_active = true
        AND rc.role_key = 'practice_manager'
    )
$$;

-- from 20251219175040_5e25a263-0649-459e-9d43-09b8774f5e01.sql
-- Fix RLS recursion on public.users by ensuring helper functions bypass row security

CREATE OR REPLACE FUNCTION public.current_practice_id()
RETURNS uuid
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO 'public'
SET row_security = off
AS $$
  SELECT u.practice_id
  FROM public.users u
  WHERE u.auth_user_id = auth.uid()
  LIMIT 1;
$$;

-- from 20251219175040_5e25a263-0649-459e-9d43-09b8774f5e01.sql
CREATE OR REPLACE FUNCTION public.is_current_user_master()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO 'public'
SET row_security = off
AS $$
  SELECT COALESCE(u.is_master_user, false)
  FROM public.users u
  WHERE u.auth_user_id = auth.uid()
  LIMIT 1;
$$;

-- from 20251219175040_5e25a263-0649-459e-9d43-09b8774f5e01.sql
CREATE OR REPLACE FUNCTION public.is_master_user(user_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO 'public'
SET row_security = off
AS $$
  SELECT COALESCE(u.is_master_user, false)
  FROM public.users u
  WHERE u.auth_user_id = user_id
  LIMIT 1;
$$;

-- from 20251219175040_5e25a263-0649-459e-9d43-09b8774f5e01.sql
CREATE OR REPLACE FUNCTION public.has_capability(_user_id uuid, _capability capability)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO 'public'
SET row_security = off
AS $$
  SELECT 
    -- Fallback: is_practice_manager flag grants all capabilities (temporary)
    EXISTS (
      SELECT 1 FROM public.users 
      WHERE auth_user_id = _user_id 
      AND is_practice_manager = true
    )
    OR
    -- Master users have all capabilities
    EXISTS (
      SELECT 1 FROM public.users 
      WHERE auth_user_id = _user_id 
      AND is_master_user = true
    )
    OR
    -- Check role_catalog default_capabilities
    EXISTS (
      SELECT 1
      FROM public.user_practice_roles upr
      JOIN public.users u ON u.id = upr.user_id
      JOIN public.practice_roles pr ON pr.id = upr.practice_role_id
      JOIN public.role_catalog rc ON rc.id = pr.role_catalog_id
      WHERE u.auth_user_id = _user_id
        AND pr.is_active = true
        AND _capability = ANY(rc.default_capabilities)
    )
    OR
    -- Check practice_role_capabilities overrides
    EXISTS (
      SELECT 1
      FROM public.user_practice_roles upr
      JOIN public.users u ON u.id = upr.user_id
      JOIN public.practice_roles pr ON pr.id = upr.practice_role_id
      JOIN public.practice_role_capabilities prc ON prc.practice_role_id = pr.id
      WHERE u.auth_user_id = _user_id
        AND pr.is_active = true
        AND prc.capability = _capability
    );
$$;

-- from 20251219175040_5e25a263-0649-459e-9d43-09b8774f5e01.sql
CREATE OR REPLACE FUNCTION public.has_capability(cap capability, p_id uuid DEFAULT NULL::uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO 'public'
SET row_security = off
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.user_practice_roles upr
    JOIN public.practice_roles pr ON pr.id = upr.practice_role_id
    JOIN public.role_catalog rc ON rc.id = pr.role_catalog_id
    LEFT JOIN public.practice_role_capabilities prc ON prc.practice_role_id = pr.id AND prc.capability = cap
    WHERE upr.user_id = (
        SELECT u.id
        FROM public.users u
        WHERE u.auth_user_id = auth.uid()
        LIMIT 1
      )
      AND pr.practice_id = COALESCE(p_id, public.current_practice_id())
      AND pr.is_active = true
      AND (prc.capability IS NOT NULL OR cap = ANY(rc.default_capabilities))
  );
$$;
