// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eeqfqklcdstbziedsnxc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVlcWZxa2xjZHN0YnppZWRzbnhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1MDkyMDIsImV4cCI6MjA3MTA4NTIwMn0.lakqim_C0jdMp-ofFe5fr5XJlQYw6CSAfYWZmbqw4ZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});