// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmixseikbpirsuuwxizw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtaXhzZWlrYnBpcnN1dXd4aXp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ2NTUzNDMsImV4cCI6MjEwMDIzMTM0M30.kHXSORlbCdNSORaar4MBw5-Vum7rMq89Uq889ba-Buk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});